# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/khlee/Dropbox/project/Kuang-Huei's Folder/combined_with_hand_box_video copy"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/khlee/Dropbox/project/Kuang-Huei's Folder/combined_with_hand_box_video copy"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/khlee/Dropbox/project/Kuang-Huei's Folder/combined_with_hand_box_video copy/CMakeFiles" "/Users/khlee/Dropbox/project/Kuang-Huei's Folder/combined_with_hand_box_video copy/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/khlee/Dropbox/project/Kuang-Huei's Folder/combined_with_hand_box_video copy/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

CameraCalibration.o: CameraCalibration.cpp.o
.PHONY : CameraCalibration.o

# target to build an object file
CameraCalibration.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CameraCalibration.cpp.o
.PHONY : CameraCalibration.cpp.o

CameraCalibration.i: CameraCalibration.cpp.i
.PHONY : CameraCalibration.i

# target to preprocess a source file
CameraCalibration.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CameraCalibration.cpp.i
.PHONY : CameraCalibration.cpp.i

CameraCalibration.s: CameraCalibration.cpp.s
.PHONY : CameraCalibration.s

# target to generate assembly for a file
CameraCalibration.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CameraCalibration.cpp.s
.PHONY : CameraCalibration.cpp.s

GeometryTypes.o: GeometryTypes.cpp.o
.PHONY : GeometryTypes.o

# target to build an object file
GeometryTypes.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GeometryTypes.cpp.o
.PHONY : GeometryTypes.cpp.o

GeometryTypes.i: GeometryTypes.cpp.i
.PHONY : GeometryTypes.i

# target to preprocess a source file
GeometryTypes.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GeometryTypes.cpp.i
.PHONY : GeometryTypes.cpp.i

GeometryTypes.s: GeometryTypes.cpp.s
.PHONY : GeometryTypes.s

# target to generate assembly for a file
GeometryTypes.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GeometryTypes.cpp.s
.PHONY : GeometryTypes.cpp.s

Marker.o: Marker.cpp.o
.PHONY : Marker.o

# target to build an object file
Marker.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Marker.cpp.o
.PHONY : Marker.cpp.o

Marker.i: Marker.cpp.i
.PHONY : Marker.i

# target to preprocess a source file
Marker.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Marker.cpp.i
.PHONY : Marker.cpp.i

Marker.s: Marker.cpp.s
.PHONY : Marker.s

# target to generate assembly for a file
Marker.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Marker.cpp.s
.PHONY : Marker.cpp.s

MarkerDetector.o: MarkerDetector.cpp.o
.PHONY : MarkerDetector.o

# target to build an object file
MarkerDetector.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MarkerDetector.cpp.o
.PHONY : MarkerDetector.cpp.o

MarkerDetector.i: MarkerDetector.cpp.i
.PHONY : MarkerDetector.i

# target to preprocess a source file
MarkerDetector.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MarkerDetector.cpp.i
.PHONY : MarkerDetector.cpp.i

MarkerDetector.s: MarkerDetector.cpp.s
.PHONY : MarkerDetector.s

# target to generate assembly for a file
MarkerDetector.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/MarkerDetector.cpp.s
.PHONY : MarkerDetector.cpp.s

TinyLA.o: TinyLA.cpp.o
.PHONY : TinyLA.o

# target to build an object file
TinyLA.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/TinyLA.cpp.o
.PHONY : TinyLA.cpp.o

TinyLA.i: TinyLA.cpp.i
.PHONY : TinyLA.i

# target to preprocess a source file
TinyLA.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/TinyLA.cpp.i
.PHONY : TinyLA.cpp.i

TinyLA.s: TinyLA.cpp.s
.PHONY : TinyLA.s

# target to generate assembly for a file
TinyLA.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/TinyLA.cpp.s
.PHONY : TinyLA.cpp.s

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/camera.cpp.s
.PHONY : camera.cpp.s

handGesture.o: handGesture.cpp.o
.PHONY : handGesture.o

# target to build an object file
handGesture.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/handGesture.cpp.o
.PHONY : handGesture.cpp.o

handGesture.i: handGesture.cpp.i
.PHONY : handGesture.i

# target to preprocess a source file
handGesture.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/handGesture.cpp.i
.PHONY : handGesture.cpp.i

handGesture.s: handGesture.cpp.s
.PHONY : handGesture.s

# target to generate assembly for a file
handGesture.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/handGesture.cpp.s
.PHONY : handGesture.cpp.s

myImage.o: myImage.cpp.o
.PHONY : myImage.o

# target to build an object file
myImage.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/myImage.cpp.o
.PHONY : myImage.cpp.o

myImage.i: myImage.cpp.i
.PHONY : myImage.i

# target to preprocess a source file
myImage.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/myImage.cpp.i
.PHONY : myImage.cpp.i

myImage.s: myImage.cpp.s
.PHONY : myImage.s

# target to generate assembly for a file
myImage.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/myImage.cpp.s
.PHONY : myImage.cpp.s

roi.o: roi.cpp.o
.PHONY : roi.o

# target to build an object file
roi.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/roi.cpp.o
.PHONY : roi.cpp.o

roi.i: roi.cpp.i
.PHONY : roi.i

# target to preprocess a source file
roi.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/roi.cpp.i
.PHONY : roi.cpp.i

roi.s: roi.cpp.s
.PHONY : roi.s

# target to generate assembly for a file
roi.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/roi.cpp.s
.PHONY : roi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... CameraCalibration.o"
	@echo "... CameraCalibration.i"
	@echo "... CameraCalibration.s"
	@echo "... GeometryTypes.o"
	@echo "... GeometryTypes.i"
	@echo "... GeometryTypes.s"
	@echo "... Marker.o"
	@echo "... Marker.i"
	@echo "... Marker.s"
	@echo "... MarkerDetector.o"
	@echo "... MarkerDetector.i"
	@echo "... MarkerDetector.s"
	@echo "... TinyLA.o"
	@echo "... TinyLA.i"
	@echo "... TinyLA.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... handGesture.o"
	@echo "... handGesture.i"
	@echo "... handGesture.s"
	@echo "... myImage.o"
	@echo "... myImage.i"
	@echo "... myImage.s"
	@echo "... roi.o"
	@echo "... roi.i"
	@echo "... roi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

